# This is a basic workflow to help you get started with Actions

name: CI

on: 
  workflow_dispatch:
    inputs:
      model_path:
        description: 'model path (gs://xxxx.h5)'     
        required: true
      model_tag:
        description: 'model tag'     
        required: true
        
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: mnist_classifier_bento
          tags: ${{ github.event.inputs.model_tag }}
          registry: ghcr.io
          dockerfile: Dockerfile
          directory: .
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN}}
          buildArgs: MODEL_PATH_ARG=${{ github.event.inputs.model_path }}
          addLatest: true
        
